remote_theme: jeromelachaud/grayscale-theme

title: VIZION
description: Advanced Computer Vision Services
# name: Nikolaos Zioulis P.C.
email: vizion.smpc@gmail.com
url: https://vizionlab.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: VIZION Single Member P.C., Straitsa 2, Thessaloniki, Greece

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://
#  - title: bitbucket
#    url: http://
#  - title: github
#    url: https://github.com/

# Build settings
markdown: kramdown
permalink: pretty
